
const RecentPost = [
    {
        id: 1,
        link: "https://media.istockphoto.com/photos/the-sales-department-scores-again-picture-id1291751221?b=1&k=20&m=1291751221&s=170667a&w=0&h=PcMe7k0T31nY5_lGAK_c6Us9g4iwGAIg47OVzthSBpk=",
        header: "Many important brands have given us their trust",
        subHeading1: "Many important brands have given us their trust",
        subPara1: "It is a well-known fact that when any discussion on lead generation takes place, quality conquers over the measure. Though it is clearly known fact that people do not like when they are pressurized into buying something, a recent research threw open some startling and revealing information.",
        subHeadin2: "Email Marketing as Lead Generation Tactics of B2B",
        subpara2: "Email marketing was the most popular among all other lead generation tactics primarily due to the ease of its implementation and for producing the desired effective results. Content marketing was found relatively difficult. But it was found to produce good results. It was found, it provides the market research experts to experiment on the same for a longer time and even learn the tactics of interacting with consumers. Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage.Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage. ",
        subHeading3: "Important aspects of lead nurturing campaigns",
        subpara3: "As a midway answer to these two answers, there was a third opinion about “Lead Qualification” that revealed a new aspect. Though many respondents might show interest in buying, there are very few who would really want to buy at that specific point in time. Though one can analyze all these through a specific method of experimentation there is no tool available from now on to measure or predict the same. Thus the sales department is under constant pressure to recognize and differentiate as who is a ready to buy respondent and who is just an anticipated respondent.",
        subHeadin4: "Bond of communication",
        subpara4: "Sending a clear message to the prospects that the organization has their welfare in mind and considers it as its priority by stating “How Can I help you” will go a long way in making them open up easily. Though it is not easy to please all the consumers all the time, it will definitely open up the channel of communication and bring in suggestions for new and better communication.In short, for an organization looking to bring in or develop more leads, it needs to bring in a major shift in its style of working from marketing and only sales to problem detecting and problem-solving."

    },
    {
        id: 2,
        link: "https://media.istockphoto.com/photos/design-team-discussing-plans-together-picture-id1350041645?b=1&k=20&m=1350041645&s=170667a&w=0&h=LvhLjsyW0DxJmBvUXDHPNfofF3VPlhLn25Dq8zYwIu0=",
        header: "Future where technology creates good jobs ",
        subHeading1: "Many important brands have given us their trust",
        subPara1: "It is a well-known fact that when any discussion on lead generation takes place, quality conquers over the measure. Though it is clearly known fact that people do not like when they are pressurized into buying something, a recent research threw open some startling and revealing information.",
        subHeadin2: "Email Marketing as Lead Generation Tactics of B2B",
        subpara2: "Email marketing was the most popular among all other lead generation tactics primarily due to the ease of its implementation and for producing the desired effective results. Content marketing was found relatively difficult. But it was found to produce good results. It was found, it provides the market research experts to experiment on the same for a longer time and even learn the tactics of interacting with consumers. Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage.Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage. ",
        subHeading3: "Important aspects of lead nurturing campaigns",
        subpara3: "As a midway answer to these two answers, there was a third opinion about “Lead Qualification” that revealed a new aspect. Though many respondents might show interest in buying, there are very few who would really want to buy at that specific point in time. Though one can analyze all these through a specific method of experimentation there is no tool available from now on to measure or predict the same. Thus the sales department is under constant pressure to recognize and differentiate as who is a ready to buy respondent and who is just an anticipated respondent.",
        subHeadin4: "Bond of communication",
        subpara4: "Sending a clear message to the prospects that the organization has their welfare in mind and considers it as its priority by stating “How Can I help you” will go a long way in making them open up easily. Though it is not easy to please all the consumers all the time, it will definitely open up the channel of communication and bring in suggestions for new and better communication.In short, for an organization looking to bring in or develop more leads, it needs to bring in a major shift in its style of working from marketing and only sales to problem detecting and problem-solving."


    },
    {
        id: 3,
        link: "https://media.istockphoto.com/photos/were-sure-that-youll-get-us-the-best-deal-picture-id1294144619?b=1&k=20&m=1294144619&s=170667a&w=0&h=iH1MSs_LIsbM-pjzuPsow8idLuEEqzCK05fyHkDUBWA=",
        header: "What you do today can improve all your tomorrows",
        subHeading1: "Many important brands have given us their trust",
        subPara1: "It is a well-known fact that when any discussion on lead generation takes place, quality conquers over the measure. Though it is clearly known fact that people do not like when they are pressurized into buying something, a recent research threw open some startling and revealing information.",
        subHeadin2: "Email Marketing as Lead Generation Tactics of B2B",
        subpara2: "Email marketing was the most popular among all other lead generation tactics primarily due to the ease of its implementation and for producing the desired effective results. Content marketing was found relatively difficult. But it was found to produce good results. It was found, it provides the market research experts to experiment on the same for a longer time and even learn the tactics of interacting with consumers. Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage.Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage. ",
        subHeading3: "Important aspects of lead nurturing campaigns",
        subpara3: "As a midway answer to these two answers, there was a third opinion about “Lead Qualification” that revealed a new aspect. Though many respondents might show interest in buying, there are very few who would really want to buy at that specific point in time. Though one can analyze all these through a specific method of experimentation there is no tool available from now on to measure or predict the same. Thus the sales department is under constant pressure to recognize and differentiate as who is a ready to buy respondent and who is just an anticipated respondent.",
        subHeadin4: "Bond of communication",
        subpara4: "Sending a clear message to the prospects that the organization has their welfare in mind and considers it as its priority by stating “How Can I help you” will go a long way in making them open up easily. Though it is not easy to please all the consumers all the time, it will definitely open up the channel of communication and bring in suggestions for new and better communication.In short, for an organization looking to bring in or develop more leads, it needs to bring in a major shift in its style of working from marketing and only sales to problem detecting and problem-solving."

    },
    {
        id: 4,
        link: "https://media.istockphoto.com/photos/mid-adult-mom-invests-time-to-teach-son-picture-id1273041079?b=1&k=20&m=1273041079&s=170667a&w=0&h=krrGQRcViL0m2y_oCB3Ufe5j5zd10Udb9wVTB6RDQkQ=",
        header: "Money markets rates finding the best accounts",
        subHeading1: "Many important brands have given us their trust",
        subPara1: "It is a well-known fact that when any discussion on lead generation takes place, quality conquers over the measure. Though it is clearly known fact that people do not like when they are pressurized into buying something, a recent research threw open some startling and revealing information.",
        subHeadin2: "Email Marketing as Lead Generation Tactics of B2B",
        subpara2: "Email marketing was the most popular among all other lead generation tactics primarily due to the ease of its implementation and for producing the desired effective results. Content marketing was found relatively difficult. But it was found to produce good results. It was found, it provides the market research experts to experiment on the same for a longer time and even learn the tactics of interacting with consumers. Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage.Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage. ",
        subHeading3: "Important aspects of lead nurturing campaigns",
        subpara3: "As a midway answer to these two answers, there was a third opinion about “Lead Qualification” that revealed a new aspect. Though many respondents might show interest in buying, there are very few who would really want to buy at that specific point in time. Though one can analyze all these through a specific method of experimentation there is no tool available from now on to measure or predict the same. Thus the sales department is under constant pressure to recognize and differentiate as who is a ready to buy respondent and who is just an anticipated respondent.",
        subHeadin4: "Bond of communication",
        subpara4: "Sending a clear message to the prospects that the organization has their welfare in mind and considers it as its priority by stating “How Can I help you” will go a long way in making them open up easily. Though it is not easy to please all the consumers all the time, it will definitely open up the channel of communication and bring in suggestions for new and better communication.In short, for an organization looking to bring in or develop more leads, it needs to bring in a major shift in its style of working from marketing and only sales to problem detecting and problem-solving."

    },
    {
        id: 5,
        link: "https://media.istockphoto.com/photos/businessmen-working-on-financial-data-on-a-digital-tablet-picture-id1324592024?b=1&k=20&m=1324592024&s=170667a&w=0&h=OmgLcvd3DerUWBIeywtTpR0wvE2vb1mHKHmp92JXm_g=",
        header: "Attract and retain quality high paying customers",
        subHeading1: "Many important brands have given us their trust",
        subPara1: "It is a well-known fact that when any discussion on lead generation takes place, quality conquers over the measure. Though it is clearly known fact that people do not like when they are pressurized into buying something, a recent research threw open some startling and revealing information.",
        subHeadin2: "Email Marketing as Lead Generation Tactics of B2B",
        subpara2: "Email marketing was the most popular among all other lead generation tactics primarily due to the ease of its implementation and for producing the desired effective results. Content marketing was found relatively difficult. But it was found to produce good results. It was found, it provides the market research experts to experiment on the same for a longer time and even learn the tactics of interacting with consumers. Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage.Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage. ",
        subHeading3: "Important aspects of lead nurturing campaigns",
        subpara3: "As a midway answer to these two answers, there was a third opinion about “Lead Qualification” that revealed a new aspect. Though many respondents might show interest in buying, there are very few who would really want to buy at that specific point in time. Though one can analyze all these through a specific method of experimentation there is no tool available from now on to measure or predict the same. Thus the sales department is under constant pressure to recognize and differentiate as who is a ready to buy respondent and who is just an anticipated respondent.",
        subHeadin4: "Bond of communication",
        subpara4: "Sending a clear message to the prospects that the organization has their welfare in mind and considers it as its priority by stating “How Can I help you” will go a long way in making them open up easily. Though it is not easy to please all the consumers all the time, it will definitely open up the channel of communication and bring in suggestions for new and better communication.In short, for an organization looking to bring in or develop more leads, it needs to bring in a major shift in its style of working from marketing and only sales to problem detecting and problem-solving."

    },
    {
        id: 6,
        link: "https://media.istockphoto.com/photos/encouraging-therapist-talks-with-young-woman-picture-id1034426836?b=1&k=20&m=1034426836&s=170667a&w=0&h=KqHBUfz0bD5m6ubAJLb4dHMGF1nCiuolt7P2YQnAXVM=",
        header: "Solutions for all small and large business people",
        subHeading1: "Many important brands have given us their trust",
        subPara1: "It is a well-known fact that when any discussion on lead generation takes place, quality conquers over the measure. Though it is clearly known fact that people do not like when they are pressurized into buying something, a recent research threw open some startling and revealing information.",
        subHeadin2: "Email Marketing as Lead Generation Tactics of B2B",
        subpara2: "Email marketing was the most popular among all other lead generation tactics primarily due to the ease of its implementation and for producing the desired effective results. Content marketing was found relatively difficult. But it was found to produce good results. It was found, it provides the market research experts to experiment on the same for a longer time and even learn the tactics of interacting with consumers. Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage.Thus it is well-known that email ranks as one of the most cost-effective as well as best conversion providing lead generation tactics in B2B. Before loading up a number of messages into the inbox of the prospect, it is essential to encourage and support the different leads in the funnel at this stage. ",
        subHeading3: "Important aspects of lead nurturing campaigns",
        subpara3: "As a midway answer to these two answers, there was a third opinion about “Lead Qualification” that revealed a new aspect. Though many respondents might show interest in buying, there are very few who would really want to buy at that specific point in time. Though one can analyze all these through a specific method of experimentation there is no tool available from now on to measure or predict the same. Thus the sales department is under constant pressure to recognize and differentiate as who is a ready to buy respondent and who is just an anticipated respondent.",
        subHeadin4: "Bond of communication",
        subpara4: "Sending a clear message to the prospects that the organization has their welfare in mind and considers it as its priority by stating “How Can I help you” will go a long way in making them open up easily. Though it is not easy to please all the consumers all the time, it will definitely open up the channel of communication and bring in suggestions for new and better communication.In short, for an organization looking to bring in or develop more leads, it needs to bring in a major shift in its style of working from marketing and only sales to problem detecting and problem-solving."

    },

]

export default RecentPost;